### PR TITLE
Add support for light and dark themes

### PR DESCRIPTION
**Pull request by Abhishekkumar2021**
## Dark Mode support
image

## Light Mode support
image

### CODE REVIEW

**Comment by Samuel-Aktar-Laskar** [comment]
Nice, will merge it soon.

**Comment by Abhishekkumar2021** [comment]
Please look into this😊

**Comment by Abhishekkumar2021** [comment]
Please look into this and if you found this helpful then merge it.

**Comment by Samuel-Aktar-Laskar** [comment]
> Please look into this and if you found this helpful then merge it.

The reason I was not merging is because I believe previous icons were better and familiar than these. 
Also the gradient in background seems little fancy. 

Also, abhi toh ghar aa gaya, testing karna bhi possible nhi hai.

**Comment by Abhishekkumar2021** [comment]
> > Please look into this and if you found this helpful then merge it.
> 
> The reason I was not merging is because I believe previous icons were better and familiar than these. Also the gradient in background seems little fancy.
> 
> Also, abhi toh ghar aa gaya, testing karna bhi possible nhi hai.

No issues .

**Pull request closed without merging**
